name: Auto M3U Update

on:
  schedule:
    - cron: "0 */4 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate M3U
        run: |
          curl "http://filex.homes/get.php?username=1month&password=1month&type=m3u_plus" -o playlist.m3u

      - name: Commit & Push
        run: |
          git config --global user.name "bot"
          git config --global user.email "bot@example.com"
          git add playlist.m3u
          git commit -m "Update playlist" || echo "No changes"
          git push
