name: Cookie Update Bot

on:
  schedule:
    - cron: '0 */3 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Requests
        run: pip install requests

      - name: Run Script
        run: python update_cookie.py

      - name: Commit & Push
        run: |
          git config user.name "Bot"
          git config user.email "bot@github.com"
          git add prr.m3u || echo "No file"
          git commit -m "Auto Update" || echo "No changes"
          git push
