name: Auto M3U Generator

on:
  push:
    paths:
      - 'channels.txt'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Generate M3U file
        run: |
          echo "#EXTM3U" > playlist.m3u

          while IFS=',' read -r name url
          do
            echo "#EXTINF:-1,$name" >> playlist.m3u
            echo "$url" >> playlist.m3u
          done < channels.txt

      - name: Commit & Push
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add playlist.m3u
          git commit -m "Auto M3U update" || echo "No changes"
          git push
